### ISSUE TITLE
Manual install doesn't upgrade anymore

### ISSUE THREAD

**Issue by Firesphere** [motioneye-project/motioneye#1218]
I've installed MotionEye according to the manual installation instructions.

After running all the commands to manually upgrade, the interface still claims it's an older version, despite the output from the terminal happily says it's the latest stable version.

**Comment by ccrisan** [comment]
@Firesphere have you restarted the motionEye server?

**Comment by Firesphere** [comment]
Hi @ccrisan ,

This is quite an old issue, that has long been resolved and I forgot I made an issue for...
