### ISSUE TITLE
Migrate issue 

### ISSUE THREAD

**Issue by devils27** [motioneye-project/motioneye#1237]
Issue using migrateconf.sh script. Keep getting
 pi@raspberrypi:/etc/motioneye $ ./migrateconf.sh
./migrateconf.sh: line 71: syntax error near unexpected token `.*'
./migrateconf.sh: line 71: `thread-(.*)\.conf ]]; then'

Even when made executable and script ran inside the motioneye directory and also when script directed towards conf file (ie.  
./migrateconf.sh motion.conf, etc..

**Comment by ccrisan** [comment]
@devils27 what does `/bin/bash --version` say?

**Comment by devils27** [comment]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
