### ISSUE TITLE
Question re: Uploading to Amazon S3

### ISSUE THREAD

**Issue by NginUS** [motioneye-project/motioneye#1293]
I have an Amazon bucket mounted locally using s3fs, & scheduled a 'cp' script to run periodically to mirror files there.

I currently have it running every few hours, & have yet to see how it deals with partially written local files. Even if it updates those properly, I'd prefer to have something running to constantly mirror in realtime so as to eliminate the gap.

Part of the script includes a 'df' to be sure the remote bucket is actually mounted to prevent filling /mnt/foo on sda accidentally. And I have no idea how I can get something to safely mirror all the time the way I have in mind.

I tried setting the 'File Storage' section to 'Upload Media Files' to a path on 127.0.0.1 via sftp, but it didn't work. Even if it did, it wouldn't be able to check for a successful remote mount before going ahead with the 'upload', so there's that being less than ideal.

I'm open to ideas in case anyone knows how to pull this off.

TIA...

**Comment by MichaIng** [comment]
Implemented for next release/current `dev` branch: #2376
Would be great if you could test it, here are `dev` install instructions: https://github.com/motioneye-project/motioneye/tree/dev#installation
