### ISSUE TITLE
i cant use upload to service HELP!!!

### ISSUE THREAD

**Issue by elliopitas** [motioneye-project/motioneye#158]
as you see in the video i know how to use it it just randomly works and not (in the video it worked). i changed the camera and needed to reconfigure that part to store to cloud for the new camera i did the same thing with the first one but it says accessing the upload service failed
[2016-03-28 22-15-30.zip](https://github.com/ccrisan/motioneye/files/192330/2016-03-28.22-15-30.zip)

**Comment by Ethocreeper** [comment]
is anybody going to help me

**Comment by ccrisan** [comment]
I made a few fixes to the cloud upload services. Could you try the latest version and see if the problem persists?
