### ISSUE TITLE
camera name error

### ISSUE THREAD

**Issue by cinnamonsweets** [motioneye-project/motioneye#1862]
motionEye Version | 0.42.1
Motion Version | 4.2.2
OS Version | Raspbian 10

Video Device > Camera Name
motioneye.service fails to start on boot if I set camera name to just a number.

**Comment by zagrim** [comment]
Duplicate of #1546.

**Comment by ccrisan** [comment]
motionEye has a design issue when it comes to dealing with motion configuration and data types: it will automatically coerce numeric strings to numbers (integers and floats). This particular issue is going to be a bit more difficult to solve.

**Comment by MichaIng** [comment]
Fixed with: #2344
