### ISSUE TITLE
LICENSE file missing in pypi tarball

### ISSUE THREAD

**Issue by rustypig91** [motioneye-project/motioneye#2257]
I could not find any license text inside https://files.pythonhosted.org/packages/c5/ff/139b4b02ed089b2b50eee65d1059ae0d29064ab5f4ad429e45c702396697/motioneye-0.42.1.tar.gz

**Comment by starbasessd** [comment]
License, as in is motionEye using a version of GPL or similar?

**Comment by rustypig91** [comment]
The [LICENCE](https://github.com/ccrisan/motioneye/blob/dev/LICENSE) file could be included in the pypi package

**Comment by MichaIng** [comment]
Makes sense. I guess @jmichault and/or @cclauss would know best how to achieve this. Else I can have a closer look when we are closer to a new stable release.

I first thought it may be best to clearly separate the actual code from meta files, including sample configs, service files etc, but probably it is even good to include all meta files into the resulting Python module, basically moving the content of `motioneye` sub directory into the parent? But if wanted, that should be done with case when ready pull requests  have been merged, as it causes a lot of conflicts.

**Comment by MichaIng** [comment]
Solved in `dev` via #2346. But it may take a while until we do a new PyPI release. Marking this as closed.
