### ISSUE TITLE
build: pyproject.toml vs requirements.txt

### ISSUE THREAD

**Issue by cclauss** [motioneye-project/motioneye#2323]
@jmichault What is your recommendation for building this project?
* [ ] https://python-poetry.org
* [ ] https://flit.readthedocs.io
* [ ] Other?

The current GitHub Action is doing `pip install -r requirements.txt` but that does not take advantage of `pyproject.toml` and `setup.cfg`.

How would you suggest that our GitHub Actions build the project to leverage these files?

**Comment by jmichault** [comment]
No preference. I have made pyproject.toml and setup.cfg because it's recommended, but i have only used `python3 -m build` and `twine  upload`. Never used more advanced tools, you are more experienced than me for this part, so choose the most appropriate.

**Comment by cclauss** [comment]
I have never used https://pypi.org/project/build so thank you for teaching me about it.
