### ISSUE TITLE
Eufy camera not working

### ISSUE THREAD

**Issue by fxtv1060** [motioneye-project/motioneye#2329]
I installed ME on a Cubox i running Armbian (Bulleye) When trying to connect one of my Eufy 2 cameras here is what I get: 

![image](https://user-images.githubusercontent.com/101332692/157863641-847014e4-734b-4b97-bcca-da684b758553.png)

I got the info from the Eufy app:

![image](https://user-images.githubusercontent.com/101332692/157864856-ff50f5d2-b0fd-4176-b565-06e0241b991f.png)

Any advice?

François-Xavier

**Comment by starbasessd** [comment]
If you use the http:// URL try using 
http://192.168.1.9:554
If you want to use the RTSP feed, use
rtsp://192.168.1.9/live1
both with username: admin
and password: admin
Let us know...

**Comment by fxtv1060** [comment]
Thanks! The RSTP option works. Great!

fx

**Comment by starbasessd** [comment]
Don't forget to close this.
