### ISSUE TITLE
What shebang should motioneye/scripts/po2json have?

### ISSUE THREAD

**Issue by cclauss** [motioneye-project/motioneye#2342]
@jmichault It would be good to enable [`check-executables-have-shebangs`](https://github.com/pre-commit/pre-commit-hooks#check-executables-have-shebangs) in our pre-commit at https://github.com/motioneye-project/motioneye/blob/dev/.pre-commit-config.yaml#L6 but I am unsure the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) should be for `motioneye/scripts/po2json`

**Comment by MichaIng** [comment]
This is actually a shell script:
```sh
#!/bin/sh
```
The major part of the code is an `awk` script, but embedded in the shell pipe 😉.
