### ISSUE TITLE
Make language selection a UI setting

### ISSUE THREAD

**Issue by MichaIng** [motioneye-project/motioneye#2355]
I see currently the language is chosen based on LANGUAGE environment variable. I vote for making this a UI setting, which isn't hard to achieve, I guess. It could be a motioneye.conf setting. Options:
1. Use a single choice for login, admin and surveillance users in the Preferences section.
2. Make it dedicated choices for admin and surveillance users in the General Settings section, below the Password settings.
3. Make it even three different choices for login, admin and surveillance users. The language for the login screen could be selected right from the login screen. Not sure whether it makes sense to store this as dedicated setting, like for a language which both users (if those are really two different persons) understand well, while each can select an own language from the UI after login.

The surveillance user btw currently fails. The password can be set but it is stored in plain text in the `motion.conf`, not sure whether this is intended. Probably it is not intended and hence authentication fails. Manually using SHA1 hash doesn't work either, login always shows "Invalid credentials.". Also an initial image is shown without authentication on port 9081, but the stream then gets killed. Something to look at separately, of course.

**Comment by jmichault** [comment]
My merge make language selection a UI setting.
But i don't close the issue because when the user change the language, he must : 
* click Apply, which cause motioneye to kill himself to force restart.
* refresh the page
* login again in motioneye

I search a more user friendly approach.
