### ISSUE TITLE
Completely unable to change passwords

### ISSUE THREAD

**Issue by TonyDicken1964** [motioneye-project/motioneye#2391]
Hi

I have tried over and again to change the admin and surveillance password. I add new passwords, click refresh, clear the cache refresh and the old default admin password remains.

What am I missing?

Thanks

Tony

**Comment by MichaIng** [comment]
Did you click "Apply" after entering the passwords? No refresh or cache clearing is required.

If so, can you please paste the service logs:
```sh
journalctl -u motioneye
```

**Comment by TonyDicken1964** [comment]
Thanks, that worked fine. Can't understand why that didn't work up to now!

**Comment by MichaIng** [comment]
One little quirk I also recognised is that the "Apply" button does not appear while you are typing the new password but only when you then select a different field. Would be actually better to show it once you type in something, so it cannot be overseen.

**Comment by TonyDicken1964** [comment]
Totally agree.

⁣Get BlueMail for Android ​

On 26 Mar 2022, 15:18, at 15:18, MichaIng ***@***.***> wrote:
>One little quirk I also recognised is that the "Apply" button does not
>appear while you are typing the new password but only when you then
>select a different field. Would be actually better to show it once you
>type in something, so it cannot be overseen.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/motioneye-project/motioneye/issues/2391#issuecomment-1079703633
>You are receiving this because you modified the open/close state.
>
>Message ID:
***@***.***>
