### ISSUE TITLE
Poor stream quality for 'surveillance' user, improves when logged in as 'admin' user

### ISSUE THREAD

**Issue by robertcrews** [motioneye-project/motioneye#2405]
Motioneye 0.42.1 running on Raspberry Pi.  When connecting to motionEye web page I am presented with the stream from my cameras with very poor quality.  If I log in as the 'admin' user the quality becomes much better.  If I log off from 'admin' and log back in as 'user' the quality is poor.  Why is this happening?

**Comment by zagrim** [comment]
Without knowing what "very poor quality" exactly looks like: Have you by chance set Resolution Dimmer under Preferences to very low value for surveillance user? That's about the only thing I could think of that should affect stream quality per user.

**Comment by robertcrews** [comment]
It was the resolution dimmer, thanks!
