### ISSUE TITLE
Motion Notification Web Hook URL is reset to default after restarting Home Assistant

### ISSUE THREAD

**Issue by sesardelaisla** [motioneye-project/motioneye#2406]
I have been using MotionEye a few months ago. I have realized that the Web Hook URL field below Motion Notification section is reset to default after restarting Home Assistant. Is it possible to fix this behaviour? Thanks!

**Comment by MichaIng** [comment]
With plain motionEye this is not the case, hence I suggest you ask this on the HA addon's repository: https://github.com/hassio-addons/addon-motioneye/issues

**Comment by sesardelaisla** [comment]
Thank you for such a quick response! Actually, I just realized that field is not reset if I restart the component only, so it makes sense that the problem is in the HA integration part. I will open an issue in HA addon's repository. Cheers!
