### ISSUE TITLE
Motioneye create mediafiles with chmod 775

### ISSUE THREAD

**Issue by Forsskieken** [motioneye-project/motioneye#2415]
Hi There,

I'm running Motioneye in a lxc container on Proxmox 7
I'm running Motioneye as a normal user guyf
Mediafiles are created as guyf:guyf on a smb share with -rw-r--r--
I would like to change that so I can delete files from another PC
How can I do That?

**Comment by MichaIng** [comment]
You could add `UMask=002` to the `[Service]` section of `/etc/systemd/system/motioneye.service`.
