### ISSUE TITLE
Wrong mask setting file read for privacy mask ui values

### ISSUE THREAD

**Issue by tunkio** [motioneye-project/motioneye#2423]
If you enable both motion and privacy mask at the same time, json response for UI will contain motion mask values for both masks(motion and private). Now if you save camera settings both masks will contain same mask(motion area).

Invalid filename forming in **motioneye/utils/__init__.py** function **parse_editable_mask_file**:

```
    file_name = os.path.join(settings.CONF_PATH, 'mask_%s.pgm' % camera_id)
```

Fix:

```
    postfix = "_privacy" if mask_class == "privacy" else ""
    file_name = os.path.join(settings.CONF_PATH, f'mask_{camera_id}{postfix}.pgm')
```

**Comment by MichaIng** [comment]
Many thanks, looks right 👍. Could you open a PR with this fix?

**Comment by zagrim** [comment]
I can verify that the issue does exist, ran into it the other day but didn't have the time to look into it then and just thought it was some mixup in my dev setup (production running a release without built-in privacy mask support in ME).

**Comment by tunkio** [comment]
No problemo! I need to be more precise when reading source code. Missed that filename forming function totally, maybe due there was so many lines on it :) But good catch!

**Comment by tunkio** [comment]
This is already fixed. Closing.
