### ISSUE TITLE
Buttons for playing a saved video and playing it on higher speed (timelapse) on top of each other

### ISSUE THREAD

**Issue by zagrim** [motioneye-project/motioneye#2431]
There seem to be two icons overlapping in the center of video preview (play and timelapse "play * 5 and chain" - what a weird tooltip). This occurs in the dev branch.

The icon for timelapse is probably changed inadvertantly, since now it uses the same icon as single-camera view. I wonder if it had the "fast-forward" icon I seem to have removed in https://github.com/motioneye-project/motioneye/pull/1968/files#diff-a773ec03496a82b602d5f994a6401f5d62ecc3420d788a646c7b5da78f059d6c since I didn't realise that the icon was in use even though it wasn't present in the camera button bar.

**Comment by cryptage21** [comment]
I confirm, buttons are overlapped. 

https://i.ibb.co/z80MkQF/Buttons-Overlapped.png

**Comment by MichaIng** [comment]
Fixed in `dev` 🙂.
