### ISSUE TITLE
Privacy Mask

### ISSUE THREAD

**Issue by bad-friday** [motioneye-project/motioneye#2443]
On the Web-page is a privacy mask, under :settings:video device:privacy mask. How can this be defined?

**Comment by bad-friday** [comment]
Solution found

**Comment by MichaIng** [comment]
The privacy mask only hides the marked areas from the camera stream in motionEye. The motion mask on the other hand means that motion within these marked areas won't trigger the motion detection (an in case motion triggered recording) either.
