### ISSUE TITLE
v4l controls localization

### ISSUE THREAD

**Issue by jose1711** [motioneye-project/motioneye#2491]
At this moment it is impossible to translate v4l controls (`msgid`s are missing)
![obrázok](https://user-images.githubusercontent.com/1406222/169280808-d7845854-6edd-4383-b618-92666f4a1aa2.png)

To improve user experience it would be nice if gettext template contains a list of v4l device attributes (perhaps `v4l-info | grep name` can help here).

**Comment by jmichault** [comment]
@jose1711,
issue fixed, v4l2 controls are now included in translations (at least for the names i found).
