### ISSUE TITLE
Webhooks - POST data should be bytes

### ISSUE THREAD

**Issue by gorbunovav** [motioneye-project/motioneye#2518]
It seems that the same fix as in #2456 is required for webhooks.

Error message:

>ERROR: failed to call webhook: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.

**Comment by MichaIng** [comment]
Many thanks for your report. You should be right, another case where we need to switch to bytes for POST data. I'll have a closer look when I find time, if nobody is faster 🙂.

**Comment by MichaIng** [comment]
Solved in `dev`.
