### ISSUE TITLE
Spinup hdd and s.m.a.r.t. read when I open motioneye

### ISSUE THREAD

**Issue by Nuke142** [motioneye-project/motioneye#2551]
I use _https://hub.docker.com/r/djaydev/motioneye/_ (deleted) docker on UNRAID OS. All paths mounted to NVMe disk.
When I open motioneye website to watch my camera - both HDDs start spining, in syslog i see  read SMART.
This is bad. 99.9% of the time my hdd's should sleep.
That happens not each time. But each ~12 hours or more.

**Comment by MichaIng** [comment]
Could you verify whether it's the same with the new `dev` branch base Docker container: https://github.com/motioneye-project/motioneye/pkgs/container/motioneye

**Comment by Nuke142** [comment]
Yes, same problem. I tested few hours after install `dev` branch - no spin-ups.
After 10+ hours i access my camera again and it takes about 10 seconds because of disk spin-ups.
![image](https://user-images.githubusercontent.com/19406558/177099194-e7481b1e-d4d5-42aa-a9cc-383278e1308a.png)

**Comment by Nuke142** [comment]
I think problem only with my case. Disabled all plugins and dockers and can't repeat that problem. No spinups anymore.
I add some info if i investigate it further.
