### ISSUE TITLE
Bullseye, motionEye Version 0.43.0, Motion Version 4.3.2, working schedule not working

### ISSUE THREAD

**Issue by bulgin** [motioneye-project/motioneye#2586]
Hello.  Could use some advice.  I've set a working schedule but motioneye zips right past it and continues to operate during off schedule hours.  I've checked the clocks on the raspberry pi and the time presented in the screens of motioneye and they are all in sync and accurate for this time zone.  Can't figure out whats's wrong.

Used install from here:
https://github.com/motioneye-project/motioneye/tree/dev#installation

Any help much apprecicated.
![Untitled](https://user-images.githubusercontent.com/16614115/187570368-75c6f81a-eb01-4849-911f-6b77ff1dc3ef.png)

**Comment by zaphod24** [comment]
I've noticed the same with my setup ever since I updated to the python3 version. It just records all the time, not during the scheduled times.

**Comment by zaphod24** [comment]
No ideas?

**Comment by MichaIng** [comment]
Can you check whether `journalctl -u motioneye` contains any errors?

**Comment by MichaIng** [comment]
Let's keep this issue tracked here: #2663
I assigned a milestone as well.
