### ISSUE TITLE
IMX519 + MotionEye + RP 4b + Buster

### ISSUE THREAD

**Issue by 149113** [motioneye-project/motioneye#2593]
This is more of a general question than a bug. Is it possible to use the IMX519 16MP camera on Buster (or Bullseye) with MotionEye? Having a lot of difficulty getting this setup and don't really know if this hardware/OS/app combo will even work or is supported. Don't want to waste any more time trying if that's something that will never work. Any input appreciated

**Comment by clscoza** [comment]
Same boat! The "custom" ArduCam Libcamera is probably an issue.

**Comment by GenerallyClumsy** [comment]
I think it might be that Motoineye doesn't support libcamera for internal (ribbon) cameras. Hoping this can be fixed soon.
