### ISSUE TITLE
port forwarded version seems to open motion

### ISSUE THREAD

**Issue by soapy75** [motioneye-project/motioneye#2621]
I am using raspberry pi 02 w. 

I have no problems with the local version with two cameras
![image](https://user-images.githubusercontent.com/68105703/197355108-c331452b-e5d5-4c38-be7d-ec0c92a05479.png)

but after portforwarding, the version shows a simplified version with seems to be motion, not motion eye.
![image](https://user-images.githubusercontent.com/68105703/197355161-a1fc6faf-74b2-4609-8ae9-2c355c64fa5e.png)

I was presented with a log in pop up and managed to log (as admin)on the first time i opened it, but even after clearing cookies it no longer shows up. There is no admin or second cameras which seems to be a characteristic of the normal motion. I am still able to access the local version with no problems.

**Comment by zagrim** [comment]
Which port did you forward? 8765 (or whatever you have when locally accessing ME in the first screenshot)?

**Comment by soapy75** [comment]
Ohhhh the local port is 8765 but the forwarded is 8081, could that be the problem?

**Comment by zagrim** [comment]
By default, port 8765 is the UI of MotionEye, 8081 is the streaming port of the camera #1. So yes, I think you've basically just forwarded the streaming URL of the first camera, and the issue should be corrected if you forwarded port 8765 instead.

**Comment by soapy75** [comment]
Yes i just worked it out, thanks for the help!
