### ISSUE TITLE
Gray screen with "unable to open video device since..."

### ISSUE THREAD

**Issue by Pikachu0023** [motioneye-project/motioneye#2627]
I am using:
RPi OS Lite (Legacy) (Buster) Raspbian 10
RPi 4B 4GB
motionEye Version | 0.42.1
Motion Version | 4.3.2
Camera: Longruner CSI for Raspberry Pi 4 
Camera Model: LC26-US
Camera Model Name: OV5647

![image](https://user-images.githubusercontent.com/95501346/199294528-56727645-8ad8-4174-be78-a4e9274c0ba5.png)
![image](https://user-images.githubusercontent.com/95501346/199294088-9ec7cb91-64f4-4dd4-a5a0-ed2cd47a7880.png)

![image](https://user-images.githubusercontent.com/95501346/199294141-60d8874b-0d49-401d-8a31-c17b2196f234.png)

**Comment by RealDekkia** [comment]
Woul've been nice if you wrote how you fixed it.
