### ISSUE TITLE
No recordings

### ISSUE THREAD

**Issue by Ryan5374** [motioneye-project/motioneye#2672]
I installed motioneye using the ubuntu tutorial on a linux mint system. Everything works fine, motion detection even shows the red boxes when movements are made, but there are never any videos recorded. I have file storage to a local directory, and motion detected recording triggers. I have the mint-meta package installed for codecs and I've tried multiple formats, including MKV and H264 MP4, but I never get any videos or photos, even when clicking the manual photo button. 
![image](https://user-images.githubusercontent.com/53656478/208994532-59a44526-b836-45d2-88d0-d8986b23b87d.png)

**Comment by zagrim** [comment]
Kind of obvious, but have to ask since you provide next to no info of your configuration: Is storing movies enabled? Is the recording mode Motion Triggered? Do the logs show any errors?

**Comment by Ryan5374** [comment]
My bad, I'll try to include that info next time. I updated my codecs and that ended up working, sorry for bothering you
