### ISSUE TITLE
May update docker image?

### ISSUE THREAD

**Issue by corincorvus** [motioneye-project/motioneye#2676]
Hi,

i try to use the docker image. its over 2 years old :/

may you can update it? the manual installation with own building dont work.

Thanks

**Comment by MichaIng** [comment]
You may use the `edge` version container from here: https://github.com/motioneye-project/motioneye/pkgs/container/motioneye
We are about to publish the Python 3 based `dev` branch of motionEye as pre-release to PyPI and a stable release along with Docker container uploads to Docker hub hopefully soon afterwards.
