### ISSUE TITLE
Can not start Motioneye after reboot.

### ISSUE THREAD

**Issue by Xadro3** [motioneye-project/motioneye#2709]
Hi, I've installed Motioneye on a pi0 yesterday and after a lot of trial and error managed to install it on raspbian buster, I followed every step in the wiki and managed to get it to run. I turned the Pi off and mounted it outside again and turned it on, but Motioneye did not start, manually starting it with 
systemctl daemon-reload
 systemctl enable motioneye
 systemctl start motioneye
Doesn't do anything either.

**Comment by Xadro3** [comment]
I get no error messages, I run as root

**Comment by MichaIng** [comment]
Please try these instructions to install the latest Python 3 compatible version: https://github.com/motioneye-project/motioneye/tree/dev#installation

**Comment by Xadro3** [comment]
I followed the Python 3 instructions, and i can see motion now being active, but i can not see any process pertaining to the webinterface, i can not connect to it via browser either.
![grafik](https://user-images.githubusercontent.com/22886138/222739855-03b7de9b-31c9-408d-91b8-74ef01e6d6ee.png)

**Comment by Xadro3** [comment]
![grafik](https://user-images.githubusercontent.com/22886138/222745479-d07e2de6-85d5-47d9-b508-aa65b928c7ed.png)
seems like a permission issue or maybe the folder was not setup?
![grafik](https://user-images.githubusercontent.com/22886138/222745636-25fff9bd-c36f-4593-a3e8-43b212793f45.png)
motion is running, but throwing permission errors for ffmpeg

**Comment by MichaIng** [comment]
Okay, first of all disable motion:
```sh
systemctl disable --now motion
```
And then I think you have an old motionEye service in place:
```sh
systemctl cat motioneye
```
Please try to replace it with the new one:
```sh
curl -sSfo /etc/systemd/system/motioneye.service 'https://raw.githubusercontent.com/motioneye-project/motioneye/dev/motioneye/extra/motioneye.systemd'
systemctl daemon-reload
systemctl restart motioneye
sleep 3
journalctl -u motioneye
```
The installer is conservative and does not replace an existing unit, but this causes more issues than it solves.

**Comment by Xadro3** [comment]
I followed your Instructions and i got some permission issues, i went into each directory to give the permissions manually, but i now get 
![grafik](https://user-images.githubusercontent.com/22886138/222788060-003a8fd8-a548-476e-acae-e4dcbea6f408.png)
a smb error which i am not sure how to fix

**Comment by MichaIng** [comment]
If you do not use it, disable the SMB mounts option: https://github.com/motioneye-project/motioneye/blob/ad21146/motioneye/extra/motioneye.conf.sample#L56-L57

I opened another issue about enabling this feature in non-root mode, which is generally possible: #2710
