### ISSUE TITLE
no previews for recorded videos on dev/edge docker

### ISSUE THREAD

**Issue by spupuz** [motioneye-project/motioneye#2795]
![image](https://github.com/motioneye-project/motioneye/assets/1721792/144fa394-b3b9-4a76-9b65-a6747d4f7fe7)

here is also attached the log

[_motioneye_logs.txt](https://github.com/motioneye-project/motioneye/files/12092802/_motioneye_logs.txt)

if anything else is needed i'm available

**Comment by spupuz** [comment]
![image](https://github.com/motioneye-project/motioneye/assets/1721792/3433da13-337d-4525-8f7d-e8f62b657a5b)

**Comment by zagrim** [comment]
Oh, I see that you've also reported this on the v0.43.0 release tracking issue (and also commented that reconfiguring cameras resolved the issue), but curiously there the problem was that "CUBIC" was not available, here it is now "LINEAR". But that detail isn't probably important.
It the docker image you are using motioneye-project/motioneye:edge ?

**Comment by zagrim** [comment]
Reconfiguring the cameras didn't help here?

**Comment by spupuz** [comment]
> Oh, I see that you've also reported this on the v0.43.0 release tracking issue (and also commented that reconfiguring cameras resolved the issue), but curiously there the problem was that "CUBIC" was not available, here it is now "LINEAR". But that detail isn't probably important. It the docker image you are using motioneye-project/motioneye:edge ?

yes it is



> Reconfiguring the cameras didn't help here?

all is working properly except preview of recorded image and also a friend of mine has the same error, the error i got before we i needed to reconfigure cam was related to stream not processed at all

**Comment by zagrim** [comment]
Ok. The LINEAR vs CUBIC thing seems just to be about whether ME is trying to create thumbnail to be used in media picker, or get the "current" image for the UI camera frame (thus, streaming). But I find it curious if some reconfiguration of the camera got rid of the latter issue, since the error (in that other issue) was "module 'PIL.Image' has no attribute 'CUBIC'" and surely existence of Pillow attributes aren't dependent on camera configs.

I think that someone with expertise on debugging the Docker image build should take a look at this. Standalone dev branch build has no issue with either of the mentioned features, so it looks like there's a wrong "Pillow" being used. I don't have the time right now to start digging into this :disappointed:

**Comment by Ryu945** [comment]
I don't remember the details but I tried changing file formats when I had issues with that.  I don't remember what I ended up fixing but I had less issues with things not being displayed.

**Comment by zethis** [comment]
According to pillow documentation the constant Image.LINEAR was replaced with Image.BILINEAR, will try to build it like this and test :)

**Comment by zethis** [comment]
Fixed, PR here: https://github.com/motioneye-project/motioneye/pull/2796

**Comment by zagrim** [comment]
@zethis nice catch, I feel kind of embarassed that I didn't think of that kind of possibility, but since I haven't seen any deprecation warnings and the version that has been installed on my setup has not had any issue, that didn't occur to me at all.

**Comment by zethis** [comment]
Fix the version in requirements.txt could be a nice thing ?

**Comment by zagrim** [comment]
I don't know how pythonistas generally manage their dependency versions, and if something like that is wanted in ME. Does @MichaIng have an opinion?

And I'd really like to know if and how one is supposed to see warnings for usage of deprecated Python library features, or if the reason for me not noticing any is Debian's python3-pil which has un-deprecated those constants.

**Comment by spupuz** [comment]
When will the pr fix be merged in the docker image?

**Comment by zethis** [comment]
> I don't know how pythonistas generally manage their dependency versions, and if something like that is wanted in ME. Does @MichaIng have an opinion?
> 
> And I'd really like to know if and how one is supposed to see warnings for usage of deprecated Python library features, or if the reason for me not noticing any is Debian's python3-pil which has un-deprecated those constants.

Like this in requierements.txt
Pillow==10.0.0

What i notice too is the requierements.txt file is not used in the Dockerfile to build the docker image, so this way pillow will be installed at the last version everytime the docker image will be rebuilded.

**Comment by spupuz** [comment]
Is the pr merged? I got a docker update yesterday but the problem persists.

**Comment by zoidy** [comment]
Would really love to see this merged. I applied the code changes manually to the running Docker container and it fixes the issue.

**Comment by spupuz** [comment]
> Would really love to see this merged. I applied the code changes manually to the running Docker container and it fixes the issue.

Me too honestly appreciate the great work the team and the community is doing but not having a formal release with proper versioning is driving me crazy can't understand what is the status of the project and the next steps.

**Comment by Nuke142** [comment]
> > Would really love to see this merged. I applied the code changes manually to the running Docker container and it fixes the issue.
> 
> Me too honestly, I appreciate the great work the team and the community is doing but not having a formal release with proper versioning is driving me crazy can't understand what is the status of the project and the next steps.

Mee too. I'am mad because of this
![image](https://github.com/motioneye-project/motioneye/assets/19406558/8701ba8b-cce5-49bf-a452-32c8ef389371)

**Comment by spupuz** [comment]
> > > Would really love to see this merged. I applied the code changes manually to the running Docker container and it fixes the issue.
> > 
> > 
> > Me too honestly, I appreciate the great work the team and the community is doing but not having a formal release with proper versioning is driving me crazy can't understand what is the status of the project and the next steps.
> 
> Mee too. Mad because I see this last half (?) year ![image](https://user-images.githubusercontent.com/19406558/263674804-8701ba8b-cce5-49bf-a452-32c8ef389371.png)

i see that docker images are refreshed but no fix has happened.

**Comment by Nuke142** [comment]
i don't understand, can you fix that previews already @MichaIng  ?

**Comment by zetxx** [comment]
`AttributeError: module 'PIL.Image' has no attribute 'LINEAR'
   ERROR: 500 GET /movie/1/preview/2023-10-09/03-49-28.mp4?height=66&_username=??&_signature=?? (172.23.0.3) 75.66ms
   ERROR: module 'PIL.Image' has no attribute 'LINEAR'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/motioneye/handlers/movie.py", line 41, in get
    await self.preview(camera_id, filename)
  File "/usr/local/lib/python3.11/dist-packages/motioneye/handlers/movie.py", line 115, in preview
    content = mediafiles.get_media_preview(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/motioneye/mediafiles.py", line 912, in get_media_preview
    image.thumbnail((width, height), Image.LINEAR)
`

**Comment by spupuz** [comment]
still no preview working.

**Comment by zagrim** [comment]
I've now merged the fix (finally) to dev branch.

**Comment by zagrim** [comment]
...and the latest dev/edge docker images contain the fix.

**Comment by Nuke142** [comment]
> ...and the latest dev/edge docker images contain the fix.

Thank you! Works (i use via docker)
