### ISSUE TITLE
working schedule not working 0.43.0

### ISSUE THREAD

**Issue by Erpiovra87** [motioneye-project/motioneye#2815]
Hi! is that any code upgrade for this problem?
Set up working schedule from 0:00 to 5:00 every day and video recording on motion detection (during working schedule).
The result is always recording when motion is detected.

**Comment by Erpiovra87** [comment]
@ccrisan  can you help me ?

**Comment by arseniov** [comment]
**+1** to @Erpiovra87's issue.

I am running 0.43.1b1 on Docker :edge image and working schedule doesn't seem to be working at all. Whatever hour/schedule I set, motion detection is always on.

**Comment by MichaIng** [comment]
Fixed with: #2987
We'll push a new beta soon.
