### ISSUE TITLE
Installation failed Raspberry PI4 Legacy Bulleye

### ISSUE THREAD

**Issue by sirAnton** [motioneye-project/motioneye#2898]
Hello, i have tried to install motioneye as specified:
https://github.com/motioneye-project/motioneye/tree/dev#installation
Test with bookworm and legacy bullseye (same error).

` @raspi:~ $ sudo python3 -m pip install --pre motioneye
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple/
Collecting motioneye
  Downloading motioneye-0.43.1b1-py3-none-any.whl.metadata (4.1 kB)
Collecting tornado (from motioneye)
  Downloading tornado-6.4-cp38-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (2.5 kB)
Collecting jinja2 (from motioneye)
  Downloading https://www.piwheels.org/simple/jinja2/Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 834.0 kB/s eta 0:00:00
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from motioneye) (8.1.2)
Collecting pycurl (from motioneye)
  Downloading pycurl-7.45.2.tar.gz (234 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.2/234.2 kB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-9671shyl/pycurl_dbd17948445a4249998da17447710743/setup.py", line 229, in configure_unix
          p = subprocess.Popen((self.curl_config(), '--version'),
        File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9671shyl/pycurl_dbd17948445a4249998da17447710743/setup.py", line 970, in <module>
          ext = get_extension(sys.argv, split_extension_source=split_extension_source)
        File "/tmp/pip-install-9671shyl/pycurl_dbd17948445a4249998da17447710743/setup.py", line 634, in get_extension
          ext_config = ExtensionConfiguration(argv)
        File "/tmp/pip-install-9671shyl/pycurl_dbd17948445a4249998da17447710743/setup.py", line 93, in __init__
          self.configure()
        File "/tmp/pip-install-9671shyl/pycurl_dbd17948445a4249998da17447710743/setup.py", line 234, in configure_unix
          raise ConfigurationError(msg)
      __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

`
Any help, regards

**Comment by MichaIng** [comment]
Did you install the development headers according to the README? https://github.com/motioneye-project/motioneye/tree/dev?tab=readme-ov-file#installation

It seems libcurl headers are missing.

**Comment by sirAnton** [comment]
Thank you, now motioneye is working.
I have tried to install the compiled piwheels 32bit arm version on the 64bit os.
