### ISSUE TITLE
V4L2 device failed to open

### ISSUE THREAD

**Issue by Stormbringer906** [motioneye-project/motioneye#2908]
I have a RPI4 with a LovePI Camera Module that I'm trying to install MotionEye on.  I can run libcamera-still just fine.

When I try and setup a camera in MotionEye, I get a big list.  None of these work though.  I get V4L2 device failed to open.

![image](https://github.com/motioneye-project/motioneye/assets/155572672/bc4719d6-e3f0-41ba-8b30-439a82711e88)

Any ideas?

Thanks,
SB

**Comment by kni-bo** [comment]
Hi,
I had the same problem. The solution is libcamerify see [here](https://github.com/motioneye-project/motioneye/issues/2812).

Greetings Michael

**Comment by Stormbringer906** [comment]
Thank you VERY much.  I've been going in circles with this.

I have some old PI Zeros and an RPI 4 I've been playing with.  They now work GREAT!  On a fully updated OS!

SB
