### ISSUE TITLE
Pi 5 CSI camera failed to open

### ISSUE THREAD

**Issue by bluefish8** [motioneye-project/motioneye#2970]
I have installed motioneye on my Pi 5 using these instructions https://github.com/motioneye-project/motioneye, when connecting the ribbon camera to the Pi I get a long list of V4L2 camera but all show "unable to open camera" 
![image](https://github.com/motioneye-project/motioneye/assets/102249587/f51b15a0-3e2a-4fdf-8766-ead8ac80bb75)

Pi OS: Debian GNU/Linux 12 (bookworm)
motionEye Version:  0.43.1b1
Motion Version: 4.6.0

Motioneye log:
Apr 24 10:28:42 PiCam meyectl[933]:     INFO: adding new v4l2 camera with id 1...
Apr 24 10:28:42 PiCam motion[6611]: [0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motioneye/motion.conf
Apr 24 10:28:42 PiCam motion[6611]: [0:motion] [NTC] [ALL] config_camera: Processing camera config file camera-1.conf
Apr 24 10:28:42 PiCam motion[6611]: [0:motion] [NTC] [ALL] motion_startup: Logging to syslog
Apr 24 10:28:42 PiCam motion[6611]: [0:motion] [NTC] [ALL] motion_startup: Motion 4.6.0 Started
Apr 24 10:28:42 PiCam motion[6611]: [0:motion] [NTC] [ALL] motion_startup: Using default log type (ALL)
Apr 24 10:28:42 PiCam motion[6611]: [0:motion] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
Apr 24 10:28:42 PiCam motion[6611]: [1:ml1:Camera1] [ERR] [VID] v4l2_device_capability: Device does not support capturing.
Apr 24 10:28:42 PiCam motion[6611]: [1:ml1:Camera1] [ERR] [VID] vid_start: V4L2 device failed to open
Apr 24 10:28:42 PiCam motion[6611]: [1:ml1:Camera1] [WRN] [ALL] motion_init: Could not fetch initial image from camera
Apr 24 10:28:42 PiCam motion[6611]: [1:ml1:Camera1] [WRN] [ALL] motion_init: Motion continues using width and height from config file(s)
Apr 24 10:28:50 PiCam motion[6611]: [1:ml1:Camera1] [WRN] [ALL] mlp_retry: Retrying until successful connection with camera
Apr 24 10:28:50 PiCam motion[6611]: [1:ml1:Camera1] [ERR] [VID] v4l2_device_capability: Device does not support capturing.
Apr 24 10:28:50 PiCam motion[6611]: [1:ml1:Camera1] [ERR] [VID] vid_start: V4L2 device failed to open

Has anyone else had this issue and were able to resolve it?

**Comment by MichaIng** [comment]
See the following issues:
- #2812
- #2683
