### ISSUE TITLE
Why All camera rebots??

### ISSUE THREAD

**Issue by omumarvaishya005** [motioneye-project/motioneye#3041]
when im trying to add a new camera all other cameras are also being rebooted.
do we have any solution for this.
?????????????????????????

**Comment by zagrim** [comment]
Simply: No. At least I don't think so.

How MotionEye works is that it manages the configuration of the underlying Motion instance, and when you change the config for one camera and hit "Apply", the configuration file for that camera is written to disk. In order for Motion to  take those config file changes, it needs to be restarted, which means the processing of all camera feeds gets restarted.
