### ISSUE TITLE
Raspberry Pi5 motioneye. installation instructions

### ISSUE THREAD

**Issue by taterF15** [motioneye-project/motioneye#3075]
I followed instructions for downloading motioneyeos but i did not see a file for pi5...any assistance or links would be appreciated.

https://github.com/motioneye-project/motioneyeos/releases
https://blog.usro.net/2024/11/diy-security-camera-system-using-raspberry-pi-5/

**Comment by SuMaPa** [comment]
hi
https://github.com/motioneye-project/motioneye/issues/3057

(https://github.com/motioneye-project/motioneye?tab=readme-ov-file#installation)

BR

**Comment by MichaIng** [comment]
The moitionEyeOS has a dedicated repository: https://github.com/motioneye-project/motioneyeos
And it indeed does not support Raspberry Pi 5, as it is unmaintained for some years. To install motionEye on any other Linux distribution, SuMaPa linked the right generic instructions already.
