### ISSUE TITLE
How do I stop Motioneye from saving the photos on the SD card

### ISSUE THREAD

**Issue by nachoman245** [motioneye-project/motioneye#599]
So I set up my motioneye correctly and everything is on, I can stream and download images to my pc (with Google Drive), but I notice it's also downloading the photos to my SD too, wich I don't need at all since I already got the pictures on my PC/Server
Am using Raspian Lite as my OS with the MotionEye program installed

Thanks beforehand!

**Comment by chrisf4lc0n** [comment]
Hold on, I don't get something here... Have you got remote samba shares mounted in MotionEye and you save the files directly to your server or just Google Drive upload? The MotionEye does not save directly to the Google Drive, it only synchronises existing videos/images with the G Drive.
