### ISSUE TITLE
[Feature request] Special frame for action buttons

### ISSUE THREAD

**Issue by yanoschik** [motioneye-project/motioneye#613]
I still can't get over the limitation of the max count of visible [Action buttons](https://github.com/ccrisan/motioneye/wiki/Action-Buttons) ;) ...I'd greatly welcome having more buttons comfortably available thru the motionEye UI.
+also discussed [here](https://github.com/ccrisan/motioneye/commit/834a68233f8c162b0c77049cbd177ee053876f27)

As it's obvious, that the space inside the camera frame overlay is limited (max 8 visible buttons), it would be great to have a additional separate frame only for 'generic' action buttons - for actions not necessary bound to a specific camera.
My idea is that this could be a simple frame (just like another camera frame), optionally enabled via checkbox in _Preferences_. I would host buttons (no special graphics/icons needed) generated by a similar mechanism - loaded executable scripts placed in it's own folder (say <[configuration folder](https://github.com/ccrisan/motioneye/wiki/Configuration-File#conf_path)>/actions/). The script name would become the button title, while a prefix defines the order (e.g. script "01_Run_My_Command" --> first button named "Run My Command").
Thanks

**Comment by Matanuska** [comment]
I also need this feature, in the header bar for example
![nouveau-1](https://user-images.githubusercontent.com/14851955/44150668-b9636c7a-a08f-11e8-85de-2037af4fa7e3.jpg)

**Comment by n3roGit** [comment]
yes please

**Comment by MichaIng** [comment]
Fixed with: #2903
