### ISSUE TITLE
Enable debugging?

### ISSUE THREAD

**Issue by chrissierra** [motioneye-project/motioneye#701]
I have read that enabled debugging causes slow frame rate, How can i see if i have debugging enabled?????

**Comment by tyzbit** [comment]
If you launch `meyectl` with the` -d` option or if you have `log_level debug` in your `motioneye.conf`, then you have debugging turned on.  You should see lines in your output that start with `DEBUG:`.

If neither of those are true, and you don't see `DEBUG:` lines, then you don't have debugging turned on.

**Comment by chrissierra** [comment]
Thanks!

If it is in "quiet" mode, Uses less cpu?

**Comment by tyzbit** [comment]
It uses about the same CPU in quiet mode.
