### ISSUE TITLE
Raspbian Install Issue

### ISSUE THREAD

**Issue by smjohnson85** [motioneye-project/motioneye#809]
I kept getting an error on startup until I reinstalled with pip2. This is on latest Raspbian stretch. Would be helpful if wiki step 5 was updated to reflect need to use pip2 command.
https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian

systemctl status motioneye
● motioneye.service - motionEye Server
   Loaded: loaded (/etc/systemd/system/motioneye.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-02-28 01:42:47 PST; 12min ago
  Process: 9946 ExecStart=/usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf (code=exited, status=203/EXEC)
 Main PID: 9946 (code=exited, status=203/EXEC)

Feb 28 01:42:47 raspberrypi systemd[1]: Started motionEye Server.
Feb 28 01:42:47 raspberrypi systemd[1]: motioneye.service: Main process exited, code=exited, status=203/EXEC
Feb 28 01:42:47 raspberrypi systemd[1]: motioneye.service: Unit entered failed state.
Feb 28 01:42:47 raspberrypi systemd[1]: motioneye.service: Failed with result 'exit-code'.

**Comment by ccrisan** [comment]
Is python 3 already the default on Raspbian?

**Comment by chrisf4lc0n** [comment]
Issue command 'python' and post the results.

**Comment by smjohnson85** [comment]
Python 2.7.13 but it appears that both pip and pip2 are installed by default.

**Comment by davesdere** [comment]
Wow... I tried pip, pip3 but I didn't even know pip2 existed... I assumed that pip was pip2. Now I just tried, but it still doesn't work. Anybody got further on this?

**Comment by ccrisan** [comment]
@davesdere we have some Docker stuff that you can find in the [extra](https://github.com/ccrisan/motioneye/tree/master/extra) folder of the project. See if that works for you.

**Comment by davesdere** [comment]
Thanks @ccrisan ! I will check it out. While I'm here...
`pip2.7 install motioneye`
Solved it for me.
BTW, you did an amazing job with this UI. It's stable, simple and easy to configure. You are a pro!
