### ISSUE TITLE
motion.conf

### ISSUE THREAD

**Issue by jsavage** [motioneye-project/motioneye#847]
This is a new install on a fresh install of the latest Raspbian Stretch Full. Updated and dist-upgraded to.
I am configuring this installation headless.  I have checked that the raspicam works with raspistill.
After installing as per wiki I an not finding any ports open other than 22 which I am using and it would seem from syslog that motion.conf is not found.  This is a shame because motioneye has previous;y worked for me.
One difference is that I installed using sudo -i this time. Not sure this should matter.

I have re-installed motion and re-performed the raspbian install but to no avail.
I have made one change to motioneye.conf
```
# whether motion HTTP control interface listens on
# localhost or on all interfaces
motion_control_localhost false
```
Does anyone have any suggestions as to what I may have missed?
Are there any other diagnostics that would be useful?

```
Here is an extract from syslog:
r 29 10:06:16 raspberrypi systemd[1]: Started motionEye Server.
Mar 29 10:06:18 raspberrypi meyectl[1589]:     INFO: hello! this is motionEye server 0.38.1
Mar 29 10:06:20 raspberrypi meyectl[1589]:     INFO: main config file /etc/motioneye/motion.conf does not exist, using default values
Mar 29 10:16:09 raspberrypi motion[1689]: Stopping motion detection daemon: motionNo /usr/bin/motion found running; none killed.
Mar 29 10:16:09 raspberrypi motion[1689]: .
Mar 29 10:16:14 raspberrypi motion[1759]: Not starting motion daemon, disabled via /etc/default/motion ... (warning).
```

James

**Comment by mooniker** [comment]
Is the `motion.conf` message an error or just a message that it's using motioneye defaults for motion?

That last line looks like a lead to the reason motion is disabled.
